apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: one-time-secret
  name: one-time-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one-time-secret
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: one-time-secret
    spec:
      containers:
      - image: one-time-secret
        name: one-time-secret
        imagePullPolicy: Never
        resources: {}
        ports:
          - containerPort: 3000
status: {}
