swagger: "2.0"
info:
  description: "Vipps One Time Secret"
  version: "1.0.0"
  title: "One Time Secret"
basePath: "/vipps-ots"
tags:
  - name: "main"
    description: "Main service"
  - name: "health"
    description: "Health checks"
schemes:
  - "https"
paths:
  /:
    get:
      tags:
        - "main"
      summary: "Get the HTML page"
      description: "For looking at hypertext markup with your eyeballs."
      operationId: "getHomePage"
      produces:
        - "text/html"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Html"
        429:
          description: "too many requests"
  /api:
    post:
      tags:
        - "main"
      summary: "Create a secret"
      description: "Create a secret"
      operationId: "createSecret"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
        400:
          description: "bad request"
        401:
          description: "unauthorized"
        429:
          description: "too many requests"
        500:
          description: "internal error"
  /api/{secretId}:
    post:
      tags:
        - "main"
      summary: "Get a secret"
      description: "Get a secret"
      operationId: "getSecret"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: secretId
          type: string
          required: true
          description: the id of the secret you are looking for
      responses:
        200:
          description: "successful operation"
        400:
          description: "bad request"
        401:
          description: "unauthorized"
        429:
          description: "too many requests"
        500:
          description: "internal error"
  /health:
    get:
      tags:
        - "health"
      summary: "Determine if app is alive"
      description: "App should be considered alive if and only if response code is 200 and the 'alive' attribute in the response is set to true."
      operationId: "getAlive"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Alive"
  /ready:
    get:
      tags:
        - "health"
      summary: "Determine if app is ready to serve requests"
      description: "App should be considered ready if and only if response code is 200 and the 'ready' attribute in the response is set to true."
      operationId: "getReady"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Ready"
definitions:
  Html:
    type: "string"
  Alive:
    type: "object"
    properties:
      alive:
        type: boolean
        description: "True if service is currently alive, false if it is dead"
  Ready:
    type: "object"
    properties:
      ready:
        type: boolean
        description: "True if service is currently ready to serve requests, false if it is not"
