name: Build and Push Image
on: workflow_dispatch

jobs:
  build-push-gar:
    name: Build and Push to GAR
    runs-on: ubuntu-latest
    environment: gcp
    env:
      IMAGE_NAME: ots
      DOCKER_REPO: europe-west3-docker.pkg.dev/${{ secrets.GCP_FIRESTORE_PROJECT_ID }}/one-time-secret/ots
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Tag Release
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v minor

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      id: push
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest $DOCKER_REPO:latest
        docker tag $IMAGE_NAME:latest $DOCKER_REPO:$GIT_TAG
        docker push $DOCKER_REPO:latest
        docker push $DOCKER_REPO:$GIT_TAG

    - name: Deploy to Cloud Run
      id: deploy
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        region: europe-north1
        service: ots-cloud-run
        image: "${{ env.DOCKER_REPO }}:latest"
        # resources:
        #   limits:
        #     cpu: 1
        #     memory: "128Mi"
        env_vars: 'DATASTORE=firestore,GCP_FIRESTORE_PROJECT_ID=${{ secrets.GCP_FIRESTORE_PROJECT_ID }},GCP_FIRESTORE_COLLECTION=secrets'
        secrets: 'GCP_CLIENT_EMAIL=GCP_CLIENT_EMAIL:latest,GCP_PRIVATE_KEY=GCP_PRIVATE_KEY:latest'
