name: Build and Push Image
on:
  push:
    branches: [ main, firestore ]
jobs:
  build-push-gar:
    name: Build and Push to GAR
    runs-on: ubuntu-latest
    environment: gcp
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.IMAGE_NAME }}:latest .

    - name: Tag Release
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v minor

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        DOCKER_REPO: "${{ secrets.REPO_URL }}/${{ secrets.PROJECT_ID }}/${{ secrets.IMAGE_NAME }}"
      run: |-
        docker tag ${{ secrets.IMAGE_NAME }}:latest ${{ env.DOCKER_REPO }}:latest
        docker tag ${{ secrets.IMAGE_NAME }}:latest ${{ env.DOCKER_REPO }}:${{ env.GIT_TAG }}
        docker push ${{ env.DOCKER_REPO }}:latest
        docker push ${{ env.DOCKER_REPO }}:${{ env.GIT_TAG }}
