name: Build and Push Image
on:
  push:
    branches: [ main, firestore ]
jobs:
  build-push-gar:
    name: Build and Push to GAR
    runs-on: ubuntu-latest
    environment: gcp
    env:
      REPO_NAME: one-time-secret
      IMAGE_NAME: ots
      REPO_URL: europe-west3-docker.pkg.dev
      PROJECT_ID: key-beacon-334717
      CLOUD_RUN_SERVICE: ots-cloud-run
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Tag Release
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v minor

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      id: push
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        DOCKER_REPO: "${{ env.REPO_URL }}/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}"
      run: |-
        docker tag $IMAGE_NAME:latest $DOCKER_REPO:latest
        docker tag $IMAGE_NAME:latest $DOCKER_REPO:$GIT_TAG
        docker push $DOCKER_REPO:latest
        docker push $DOCKER_REPO:$GIT_TAG

    - name: Deploy to Cloud Run
      id: deploy
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: $CLOUD_RUN_SERVICE
        image: "${{ steps.push.env.DOCKER_REPO }}:latest"

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
