name: Build and Push Image
on:
  push:
    branches: [ main, firestore ]
jobs:
  build-push-gar:
    name: Build and Push to GAR
    runs-on: ubuntu-latest
    environment: gcp
    env:
      IMAGE_NAME: ots
      REPO_URL: europe-west3-docker.pkg.dev
      PROJECT_ID: key-beacon-334717
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Tag Release
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v minor

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        DOCKER_REPO: "$REPO_URL/$PROJECT_ID/$IMAGE_NAME"
      run: |-
        docker tag $IMAGE_NAME:latest $DOCKER_REPO:latest
        docker tag $IMAGE_NAME:latest $DOCKER_REPO:$GIT_TAG
        docker push $DOCKER_REPO:latest
        docker push $DOCKER_REPO:$GIT_TAG
